import { Toaster } from "react-hot-toast";
import { Providers } from "@/redux/provider";
import Navbar from "@/layouts/Navbar/Navbar";
import "./styles.scss";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <Toaster />
          <Navbar />
          {children}
        </body>
      </html>
    </Providers>
  );
}
